import React, { useEffect, useMemo, useState } from 'react';

const TEAMS = ['מכבי ת״א','מכבי חיפה','בית״ר י-ם','הפועל ב״ש','הפועל ת״א','מכבי נתניה','הפועל חיפה','מכבי פ״ת','בני סכנין','עירוני טבריה','הפועל ק״ש','הפועל פ״ת','הפועל ר״ג','הפועל י-ם'];
const TEAM_ICON = { 'מכבי ת״א':'🟡','מכבי חיפה':'🟢','בית״ר י-ם':'🟡⚫','הפועל ב״ש':'🔴','הפועל ת״א':'🔴⚪','מכבי נתניה':'🟡⚫','הפועל חיפה':'🔴⚫','מכבי פ״ת':'🔵','בני סכנין':'🔴','עירוני טבריה':'🔵','הפועל ק״ש':'🔵⚪','הפועל פ״ת':'🔵','הפועל ר״ג':'🔴','הפועל י-ם':'🔴⚫'};
const FIXTURES = {
  1:[['מכבי פ״ת','הפועל ק״ש'],['עירוני טבריה','הפועל פ״ת'],['הפועל י-ם','מכבי ת״א'],['מכבי חיפה','הפועל ר״ג'],['הפועל ב״ש','הפועל חיפה'],['בית״ר י-ם','הפועל ת״א'],['מכבי נתניה','בני סכנין']],
  2:[['בני סכנין','מכבי פ״ת'],['מכבי נתניה','הפועל י-ם'],['הפועל ת״א','מכבי חיפה'],['הפועל ב״ש','הפועל ר״ג'],['מכבי חיפה','מכבי ת״א'],['הפועל פ״ת','בית״ר י-ם'],['עירוני טבריה','הפועל ק״ש']],
  3:[['מכבי פ״ת','עירוני טבריה'],['הפועל ק״ש','הפועל י-ם'],['הפועל פ״ת','מכבי חיפה'],['מכבי ת״א','הפועל ב״ש'],['הפועל ר״ג','הפועל ת״א'],['הפועל חיפה','מכבי נתניה'],['בית״ר י-ם','בני סכנין']]
};
const PARTICIPANTS = Array.from({length:10},(_,i)=>`משתתף ${i+1}`);
const STORAGE_KEY='winner10-premium-v8-onefile';
const pass='2531';
const emptyData={activeUser:'משתתף 1',favoriteTeams:{},predictions:{},jokers:{},actualScores:{},admin:false};

function winnerOf(h,a){return h>a?'1':h<a?'2':'X'};
function getSaved(){try{return {...emptyData,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return emptyData}}
function App(){
  const [tab,setTab]=useState('home');
  const [now,setNow]=useState(new Date());
  const [round,setRound]=useState(1);
  const [data,setData]=useState(getSaved);
  const [toast,setToast]=useState('');
  const games=(FIXTURES[round]||FIXTURES[1]).map((g,i)=>({id:i+1,home:g[0],away:g[1],date: round===1?'22/08/26': round===2?'29/08/26':'05/09/26'}));
  useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
  useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(data))},[data]);
  const msg=(m)=>{setToast(m);setTimeout(()=>setToast(''),2200)};
  const setUser=(activeUser)=>setData(d=>({...d,activeUser}));
  const user=data.activeUser;
  const predKey=(gid)=>`${user}-${round}-${gid}`;
  const actualKey=(gid)=>`${round}-${gid}`;
  const setPred=(gid,patch)=>setData(d=>{const k=predKey(gid); const cur=d.predictions[k]||{home:0,away:0,winner:'X'}; const next={...cur,...patch}; next.winner=winnerOf(next.home,next.away); return {...d,predictions:{...d.predictions,[k]:next}}});
  const setActual=(gid,patch)=>setData(d=>{const k=actualKey(gid); const cur=d.actualScores[k]||{home:0,away:0,winner:'X',done:false}; const next={...cur,...patch}; next.winner=winnerOf(next.home,next.away); return {...d,actualScores:{...d.actualScores,[k]:next}}});
  const toggleJoker=(gid)=>setData(d=>({...d,jokers:{...d.jokers,[`${user}-${round}`]:d.jokers[`${user}-${round}`]===gid?null:gid}}));
  const scores=useMemo(()=>PARTICIPANTS.map(name=>{
    let pts=0,exact=0,dir=0,miss=0,played=0;
    Object.keys(data.actualScores).forEach(k=>{const a=data.actualScores[k]; if(!a.done)return; const parts=k.split('-'); const r=parts[0], gid=parts[1]; const p=data.predictions[`${name}-${r}-${gid}`]; if(!p)return; played++; let local=0; if(p.winner===a.winner){local+=2; dir++; if(Number(p.home)===Number(a.home)&&Number(p.away)===Number(a.away)){local+=4; exact++}} else miss++; if(String(data.jokers[`${name}-${r}`])===String(gid))local*=2; pts+=local;});
    return {name,pts,exact,dir,miss,played,team:data.favoriteTeams[name]||'לא נבחרה'};
  }).sort((a,b)=>b.pts-a.pts),[data]);
  const current=scores.find(s=>s.name===user)||scores[0];
  const time=now.toLocaleTimeString('he-IL'); const date=now.toLocaleDateString('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});
  const loginAdmin=()=>{ if(data.admin){setData(d=>({...d,admin:false}));return} const p=prompt('סיסמת מנהל'); if(p===pass)setData(d=>({...d,admin:true})); else if(p!==null)alert('סיסמה שגויה')};
  return <div className="app"><div className="wrap">
    <div className="top"><div className="hero glass"><span className="badge">🏆 Premium v8 One‑File</span><h1 className="title">10 חבר׳ה - יוספטל</h1><p className="sub">ליגת ניחושים פרטית • ניקוד • ג׳וקר • קבוצה אהודה • חוקים • טבלת דירוג</p><div className="clock"><div><span>תאריך</span><b>{date}</b></div><div><span>שעה</span><b>{time}</b></div><div><span>מחזור</span><b>{round}</b></div></div><div className="tabs"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>🏠 בית</button><button className={tab==='games'?'active':''} onClick={()=>setTab('games')}>⚽ משחקים</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>👤 אישי</button><button className={tab==='table'?'active':''} onClick={()=>setTab('table')}>📊 טבלה</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>ℹ️ חוקים</button><button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>🔧 מנהל</button></div></div></div>
    {tab==='home'&&<><div className="card glass"><h2 className="sectionTitle">ברוך הבא, {user}</h2><div className="grid2"><div className="stat"><span>נקודות</span><b>{current?.pts||0}</b></div><div className="stat"><span>קבוצה אהודה</span><b>{current?.team||'לא נבחרה'}</b></div></div><button className="btn" style={{width:'100%',marginTop:14}} onClick={()=>setTab('games')}>⚽ עבור לניחושי המחזור</button></div><Participants data={data} setUser={setUser}/></>}
    {tab==='games'&&<div className="card glass"><div className="row"><h2 className="sectionTitle">ניחושי מחזור</h2><select className="field" style={{maxWidth:135}} value={round} onChange={e=>setRound(Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>מחזור {n}</option>)}</select></div>{games.map(g=><Match key={g.id} g={g} data={data} user={user} round={round} predKey={predKey} actualKey={actualKey} setPred={setPred} setActual={setActual} toggleJoker={toggleJoker}/>) }<button className="btn" style={{width:'100%'}} onClick={()=>msg('הניחושים נשמרו בדפדפן ✅')}>💾 שמור ניחושים</button></div>}
    {tab==='profile'&&<Profile user={user} setUser={setUser} data={data} setData={setData} current={current} msg={msg}/>} 
    {tab==='table'&&<Table scores={scores}/>} 
    {tab==='rules'&&<Rules/>}
    {tab==='admin'&&<Admin data={data} setData={setData} loginAdmin={loginAdmin} msg={msg}/>} 
    {toast&&<div className="toast">{toast}</div>}
  </div></div>
}
function Participants({data,setUser}){return <div className="card glass"><h2 className="sectionTitle">👥 המשתתפים</h2><div className="grid2">{PARTICIPANTS.map((p,i)=><button key={p} className={`btn ${data.activeUser===p?'':'dark'}`} onClick={()=>setUser(p)}><div style={{fontSize:28}}>{['👑','⚽','🧤','🦁','🚀','🧠','🔥','🎯','🏆','⭐'][i]}</div>{p}<div className="small muted">{data.favoriteTeams[p]||'בחר קבוצה אהודה'}</div></button>)}</div></div>}
function Match({g,data,user,round,predKey,actualKey,setPred,setActual,toggleJoker}){const p=data.predictions[predKey(g.id)]||{home:0,away:0,winner:'X'}; const a=data.actualScores[actualKey(g.id)]||{home:0,away:0,winner:'X',done:false}; const joker=data.jokers[`${user}-${round}`]===g.id; return <div className="match"><div className="row small muted"><span>ליגת העל • {g.date}</span><button className={`btn ${joker?'':'dark'}`} onClick={()=>toggleJoker(g.id)}>{joker?'🃏 ג׳וקר פעיל':'🃏 סמן ג׳וקר'}</button></div><div className="teams"><div className="team"><div className="logo">{TEAM_ICON[g.home]||'⚽'}</div>{g.home}</div><div className="score">{p.home}:{p.away}</div><div className="team"><div className="logo">{TEAM_ICON[g.away]||'⚽'}</div>{g.away}</div></div><div className="scoreControls"><button onClick={()=>setPred(g.id,{home:Math.max(0,p.home-1)})}>-</button><b>בית</b><button onClick={()=>setPred(g.id,{home:p.home+1})}>+</button><button onClick={()=>setPred(g.id,{away:Math.max(0,p.away-1)})}>-</button><b>חוץ</b><button onClick={()=>setPred(g.id,{away:p.away+1})}>+</button></div><div className="pick">{['1','X','2'].map(x=><button key={x} className={p.winner===x?'sel':''} onClick={()=>setPred(g.id,{winner:x,home:x==='1'?1:x==='2'?0:1,away:x==='2'?1:x==='1'?0:1})}>{x}</button>)}</div>{data.admin&&<div className="rule admin"><b>מנהל: תוצאת אמת</b><div className="scoreControls"><button onClick={()=>setActual(g.id,{home:Math.max(0,a.home-1)})}>-</button><span>{a.home}</span><button onClick={()=>setActual(g.id,{home:a.home+1})}>+</button><span>:</span><button onClick={()=>setActual(g.id,{away:Math.max(0,a.away-1)})}>-</button><span>{a.away}</span><button onClick={()=>setActual(g.id,{away:a.away+1})}>+</button></div><button className="btn red" onClick={()=>setActual(g.id,{done:!a.done})}>{a.done?'פתח משחק':'סיים משחק'}</button></div>}</div>}
function Profile({user,setUser,data,setData,current,msg}){return <div className="card glass"><h2 className="sectionTitle">👤 האזור האישי</h2><label>בחר משתתף</label><select className="field" value={user} onChange={e=>setUser(e.target.value)}>{PARTICIPANTS.map(p=><option key={p}>{p}</option>)}</select><br/><br/><label>🏆 הקבוצה שאני אוהד</label><select className="field" value={data.favoriteTeams[user]||''} onChange={e=>setData(d=>({...d,favoriteTeams:{...d.favoriteTeams,[user]:e.target.value}}))}><option value="">-- בחר קבוצה --</option>{TEAMS.map(t=><option key={t}>{t}</option>)}</select><div className="grid2" style={{marginTop:12}}><div className="stat"><span>נקודות</span><b>{current?.pts||0}</b></div><div className="stat"><span>בולים</span><b>{current?.exact||0}</b></div><div className="stat"><span>כיוון</span><b>{current?.dir||0}</b></div><div className="stat"><span>פספוסים</span><b>{current?.miss||0}</b></div></div><button className="btn" style={{width:'100%',marginTop:12}} onClick={()=>msg('האזור האישי נשמר ✅')}>שמור אזור אישי</button></div>}
function Table({scores}){return <div className="card glass"><h2 className="sectionTitle">📊 טבלת דירוג</h2>{scores.map((s,i)=><div className="leader" key={s.name}><div><b>{i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1} {s.name}</b><div className="small muted">אוהד: {s.team}</div></div><b className="gold">{s.pts} נק׳</b></div>)}</div>}
function Rules(){return <div className="card glass"><h2 className="sectionTitle">ℹ️ חוקי המשחק ושיטת הניקוד</h2><div className="rule"><b>⚽ ניחוש כיוון</b><p className="muted">פגיעה ב־1 / X / 2 מזכה ב־2 נקודות.</p></div><div className="rule"><b>🎯 תוצאה מדויקת</b><p className="muted">תוצאה מדויקת מוסיפה 4 נקודות בונוס. סה״כ 6 נקודות.</p></div><div className="rule"><b>🃏 ג׳וקר מחזור</b><p className="muted">ניתן לבחור משחק ג׳וקר אחד בכל מחזור. הניקוד במשחק הזה מוכפל: כיוון נכון 4 נקודות, בול 12 נקודות.</p></div><div className="rule"><b>🔒 נעילת ניחושים</b><p className="muted">בגרסה הזו ניתן לערוך חופשי. בשלב הבא נוסיף נעילה אוטומטית לפי תאריך המשחק.</p></div><div className="rule"><b>🏆 הקבוצה שאני אוהד</b><p className="muted">כל משתתף בוחר קבוצה אהודה באזור האישי. היא מוצגת בטבלה ובכרטיס המשתתף.</p></div><div className="rule"><b>👑 בונוסים עתידיים</b><p className="muted">בהמשך נוסיף אלופה, מלך שערים ומלך בישולים עם ניקוד עונתי.</p></div></div>}
function Admin({data,setData,loginAdmin,msg}){return <div className="card glass admin"><h2 className="sectionTitle">🔧 פאנל מנהל</h2><p className="muted">סיסמת מנהל: 2531</p><button className="btn" onClick={loginAdmin}>{data.admin?'צא ממצב מנהל':'כניסה למנהל'}</button>{data.admin&&<><div className="rule"><b>ניהול תוצאות</b><p className="muted">עבור ללשונית משחקים ותראה אזור אדום לעדכון תוצאת אמת וסיום משחק.</p></div><button className="btn red" onClick={()=>{if(confirm('לאפס את כל הנתונים?')){localStorage.removeItem(STORAGE_KEY);location.reload()}}}>איפוס כל הנתונים</button></>}<button className="btn dark" style={{marginRight:8}} onClick={()=>msg('המערכת פעילה ✅')}>בדיקת מערכת</button></div>}
export default App;
